Console.WriteLine("string");
string str1 = Console.ReadLine();
string str2 = Console.ReadLine();
int str3 = (Convert.ToInt32(str1) + Convert.ToInt32(str2));
Console.WriteLine("double");
double dbl1 = Convert.ToDouble(Console.ReadLine());
double dbl2 = Convert.ToDouble(Console.ReadLine());
double dbl3 = dbl1 + dbl2;
Console.WriteLine("float");
float flt1 = Convert.ToSingle(Console.ReadLine());
float flt2 = Convert.ToSingle(Console.ReadLine());
float flt3 = flt1 + flt2;
Console.WriteLine("int");
int num1 = Convert.ToInt32(Console.ReadLine());
int num2 = Convert.ToInt32(Console.ReadLine());
int num3 = num1 + num2;
Console.WriteLine("char");
char cr1 = Convert.ToChar(Console.ReadLine());
char cr2 = Convert.ToChar(Console.ReadLine());
int cr3 = ((int)char.GetNumericValue(cr1) + (int)char.GetNumericValue(cr2));
int all = str3 + Convert.ToInt32(dbl3) + Convert.ToInt32(flt3) + num3 + cr3;
Console.WriteLine(all);